config/routes.rb
Rails.application.routes.draw do
  root "messages#index"
  resources :messages 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true, length: { in: 3..250 }

  scope :recent, -> { order(created_at: :desc) }

  # broadcasts
  # or
  # after_create_commit { broadcast_prepend_to 'messages' }
  # after_update_commit { broadcast_replace_to 'messages' }
  # after_destroy_commit { broadcast_remove_to 'messages' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :render_flash

  def render_flash
    return unless request.format.turbo_stream?
    return if response.status == 301 || response.status == 302

    Turbo::StreamsChannel.broadcast_update_to(:messages, target: :notifications, partial: 'shared/flash', locals: { flash: flash })
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  def index
    @messages = Message.recent
    @message = Message.new
  end

  def show; end

  def new
    @message = Message.new
  end

  def edit; end

  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        render_successfully_flash(:create)
        format.html { redirect_to messages_path }
        # format.html { redirect_to messages_path, notice: "Message was successfully created." }
      else
        render_error_flash
        format.turbo_stream
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @message.update(message_params)
        render_successfully_flash(:update)
        format.html { redirect_to messages_path }
        # format.html { redirect_to messages_path, notice: "Message was successfully updated." }
      else
        render_error_flash
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
    end
  end

  private

    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(:body)
    end

    def render_error_flash
      flash.now[:error] = @message.errors.full_messages.join(', ')
      render_flash
    end

    def render_successfully_flash(type)
      action_name = type == :create ? 'created' : 'updated'
      flash.now[:notice] = "Message was successfully #{action_name}!"
      render_flash
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_title(message)
    message.new_record? ? 'Create' : 'Update'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turboapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id='notifications'>
      <%= render 'shared/flash' %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/messages/_count_messages.html.erb
<h1><%= 'Message'.pluralize(Message.count) %>:
  <span id="message_counter"> <%= Message.count %> </span>
</h1>

app/views/messages/_form.html.erb
<%= form_with model: message, id: dom_id(message), target: :_top do |form| %>
  <%= render 'shared/errors', message: message %>

  <div class="field">
    <%= form.text_area :body, placeholder: 'Body', rows: '5', style: 'width: 100%; resize: vertical;' %>
  </div>

  <div style='display: flex; justify-content: flex-end; align-items: center; gap: 10px;}'>
    <%= form.submit set_title(message), style: 'max-width: 12%' %>
    <%= link_to "Cancel", messages_path if !message.new_record? || message.errors.any? %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<%= turbo_frame_tag dom_id(message) do %>

  <blockquote>
    <div>
      <strong><%= message.body %></strong>
    </div>
  </blockquote>

  <div style='display: flex; justify-content: flex-end; align-items: center; gap: 10px;}'>
    <% if action_name != "show" %>
      <%= link_to "Show", message, class: "btn-show-page",
                        data: { turbo_frame: :messages },
                        style: 'text-decoration: none;' %>
    <% else %>
      <%= link_to 'Back', messages_path, data: { turbo_frame: :messages} %>
    <% end %>
    <%= link_to "Edit", edit_message_path(message), class: 'edit-btn' %>

    <%= button_to "Destroy", message_path(message), method: :delete,
                        form: { data: { turbo_confirm: 'Are you sure?' }},
                        class: 'btn-close btn-close-white mt-2',
                        data: { turbo_frame: :messages }%>
  </div>
<% end %>

app/views/messages/create.turbo_stream.erb
<% if @message.errors.any? %>
 <%= turbo_stream.replace(@message, partial: 'messages/form', locals: { message: @message}) %>
<% end %>

app/views/messages/edit.html.erb
<%= turbo_frame_tag dom_id(@message) do %>
  <%= render 'form', message: @message %>
<% end %>

app/views/messages/index.html.erb
<%= turbo_stream_from :messages %>

<span class='time-section'>
  <%= Time.zone.now.strftime("%A, %D: %k:%M:%S.%L") %>
</span>

<%= turbo_frame_tag :messages, style: 'margin-top: 1rem;' do %>
  <div id='new_message'>
    <%= render 'messages/form', message: Message.new %>
  </div>
  <%= render 'messages/count_messages' %>
  <%= render @messages %>
<% end %>

app/views/messages/new.html.erb
<%= turbo_frame_tag dom_id(@message) do %>
  <%= render 'form', message: @message %>
<% end %>

app/views/messages/show.html.erb
<%= turbo_frame_tag :messages do %>
  <%= render @message %>
<% end %>

app/views/shared/_errors.html.erb
<% if message.errors.any? %>
  <div id="error_explanation" data-controller='autohide'>
    <h4 style='color: rgb(210, 105, 30);'>
      <%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:
    </h4>
    <ul>
      <% message.errors.each do |error| %>
        <li style='color: rgb(210, 105, 30);'><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<%#= content_tag :div, message %>
<div id="flash">
  <% flash.each do |type, message| %>
    <div class="flash-overlay fixed inset-x-0 top-0 flex items-end justify-right px-4 py-5 sm:p-5 justify-end z-30 pointer-events-none">
      <div
          data-controller="alert"
          data-alert-show-class="translate-x-0 opacity-100 bg-lemonchiffon"
          data-alert-hide-class="translate-x-full opacity-0 bg-transparent"
          class="flash-section max-w-sm w-full shadow-lg px-4 py-2 rounded relative bg-transparent border-l-8 border-sky-400 border-opacity-90 text-gray-600 pointer-events-auto transition translate-x-full transform ease-in-out duration-1000 opacity-0">
        <div class="flash-section-one p-2">
          <div class="flash-section-two flex items-start">
            <div class="flash-section-three ml-3 w-0 flex-1 pt-0.5">
              <p class="flash-section-four text-sm leading-5 font-medium">
                <%= content_tag :div, message %>
              </p>
            </div>
            <div class="flash-button-section ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="close-flash inline-flex text-gray-600 focus:outline-none focus:text-gray-300">
                <svg class="svg-close h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>